keys:
  - &ironman age1nny857q3ujh77zved353ufzte5clv444783m6jc4xthmn43r75wqcputn0
  - &royell age1et3rsqjzt2z70vt0p8p4jcm47ms8e22um57vj5nvfpss58zwlcfsmcddrt
  - &server_dns age1mcssf7calvchkh8l3kv6mjd69c46znaanlmd5dqf2e3guxv0fq6s8wm27z
  - &server_calibre age1ahfs26muknuhxeavht922e5kw009ewwjyegcrglatxn7n8rc5c2qlquffg
  - &server_gns3 age1z7p0u2ekdek8xy4zlsmczqp3xf68amrzj0nh3yx9chc6zhmxsufspdzpqe
  - &server_pve2 age1tj460ln353gy48end4dl0efqf28z2ntwxu5we7qkauw472dax9xsvmwmhq
  - &server_storage age19fwep37ruj6x7l86dfa74hxh3l8rqclghuzy6uegcummdl07juxq56au72
  - &server_traefik age1wc99wq9lztk2j8qcnej5v6gp8gfz4f0dnmzey6ncfy7yaxplr4zspnhzcs
  - &server_work_dns age14lru46n84vakjj2mjah3ewftjt33fwr2km9g75a3lcpw8af4yawq6n6uag
  - &server_work_rcm age1c8c6rdh6nrmcf4sz4jqe328v08ame6z43s3urv00552dh4a4qs4sjksfg7
  - &server_work_traefik age1crchh6h2xt6ry7p0j5pke6xcfyyfnah096dzyg7t7s48zl0hp4zqnncwd6
  - &system_friday age13exnaeq7ftcskap67kml5jgv7vxxdgjjf22f9ugypxh3jesm9ars0l9jeh
  - &system_wednesday age13xc4axyyg8wdwvtvx54cxdcfnlcwxrjcns4dfsrpe0vs0dcn8enqv8fuhz
creation_rules:
  - path: "*"
    key_groups:
      - age:
        - *ironman
        - *royell
        - *server_dns
        - *server_calibre
        - *server_gns3
        - *server_pve2
        - *server_storage
        - *server_traefik
        - *server_work_dns
        - *server_work_rcm
        - *server_work_traefik
        - *system_friday
        - *system_wednesday
