keys:
  - &ironman age1nny857q3ujh77zved353ufzte5clv444783m6jc4xthmn43r75wqcputn0
  - &royell age1et3rsqjzt2z70vt0p8p4jcm47ms8e22um57vj5nvfpss58zwlcfsmcddrt
creation_rules:
  - path: "*"
    key_groups:
      - age:
          - *ironman
          - *royell
