#!/usr/bin/env bash
echo 'Stopping Ubuntu 18.04 image...'
if distrobox list | grep 'u18' | grep -q 'Up' ; then
  distrobox stop u18
fi
sleep 1
if distrobox list | grep -q 'u18' ; then
  distrobox rm u18
fi

