#!/usr/bin/env bash
echo 'Stopping Boxkit image...'
if distrobox list | grep 'boxkit' | grep -q 'Up' ; then
  distrobox stop boxkit
fi
sleep 1
if distrobox list | grep -q 'boxkit' ; then
  distrobox rm boxkit
fi
