#!/usr/bin/env bash
echo 'Stopping Ubuntu 16.04 image...'
if distrobox list | grep 'u16' | grep -q 'Up' ; then
  distrobox stop u16
fi
sleep 1
if distrobox list | grep -q 'u16' ; then
  distrobox rm u16
fi

