require("plugins.editor.oil")
require("plugins.editor.spectre")
require("plugins.editor.hop")
require("plugins.editor.which-key")
require("plugins.editor.gitsigns")
require("plugins.editor.illuminate")
require("plugins.editor.mini")
require("plugins.editor.trouble")
require("plugins.editor.todo-comments")
require("plugins.editor.telescope")
require("plugins.editor.neo-tree")
require("plugins.editor.alpha")
require("plugins.editor.ufo")
require("plugins.editor.undotree")
require("plugins.editor.aerial")
-- require("plugins.editor.obsidian")
