{
  flake.nixosModules.droppedneedle =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      inherit (lib)
        mkEnableOption
        mkIf
        mkOption
        types
        ;
      cfg = config.ironman.droppedneedle;
    in
    {
      options.ironman.droppedneedle = {
        enable = mkEnableOption "Enable the Droppedneedle server";
        ip = mkOption {
          default = "";
          description = "Droppedneedle IP";
          type = types.str;
        };
      };
      config = {
        # Runtime
        virtualisation = mkIf cfg.enable {
          docker = {
            enable = true;
            autoPrune.enable = true;
          };
          oci-containers = {
            backend = "docker";
            # Containers
            containers."droppedneedle" = {
              image = "droppedneedle/droppedneedle:latest";
              environment = {
                "PGID" = "1000";
                "PORT" = "8688";
                "PUID" = "1000";
                "SLSKD_DOWNLOADS_PATH" = "/slskd-downloads";
                "TZ" = "America/Chicago";
              };
              ports = [
                "8688:8688/tcp"
              ];
              log-driver = "journald";
              extraOptions = [
                "--network-alias=droppedneedle"
                "--network=droppedneedle_default"
              ];
            };
          };
        };

        services.traefik.dynamicConfigOptions.http = {
          routers.droppedneedle = {
            entryPoints = "https";
            middlewares = "secured";
            rule = "Host(`droppedneedle.home.niceastman.com`)";
            service = "droppedneedle";
            tls = { };
          };
          services.droppedneedle.loadBalancer = {
            passHostHeader = true;
            servers = [
              {
                url = "http://${cfg.ip}:8688";
              }
            ];
            serversTransport = "insecure";
          };
        };
        systemd = mkIf cfg.enable {
          services = {
            "docker-droppedneedle" = {
              serviceConfig = {
                Restart = lib.mkOverride 90 "always";
                RestartMaxDelaySec = lib.mkOverride 90 "1m";
                RestartSec = lib.mkOverride 90 "100ms";
                RestartSteps = lib.mkOverride 90 9;
              };
              after = [
                "docker-network-droppedneedle_default.service"
              ];
              requires = [
                "docker-network-droppedneedle_default.service"
              ];
              partOf = [
                "docker-compose-droppedneedle-root.target"
              ];
              wantedBy = [
                "docker-compose-droppedneedle-root.target"
              ];
            };

            # Networks
            "docker-network-droppedneedle_default" = {
              path = [ pkgs.docker ];
              serviceConfig = {
                Type = "oneshot";
                RemainAfterExit = true;
                ExecStop = "docker network rm -f droppedneedle_default";
              };
              script = ''
                docker network inspect droppedneedle_default || docker network create droppedneedle_default
              '';
              partOf = [ "docker-compose-droppedneedle-root.target" ];
              wantedBy = [ "docker-compose-droppedneedle-root.target" ];
            };
          };

          # Root service
          # When started, this will automatically create all resources and start
          # the containers. When stopped, this will teardown all resources.
          targets."docker-compose-droppedneedle-root" = {
            unitConfig = {
              Description = "Root target generated by compose2nix.";
            };
            wantedBy = [ "multi-user.target" ];
          };
        };
      };
    };
}
