{
  inputs,
  moduleWithSystem,
  self,
  ...
}:
{
  flake = {
    nixosModules.soulsync = moduleWithSystem (
      perSystem@{ ... }: { lib, pkgs, ... }: {
        imports = [
          self.nixosModules.docker
        ];
        virtualisation.oci-containers.backend = "docker";

        # Containers
        virtualisation.oci-containers.containers."soulsync-webui" = {
          image = "boulderbadgedad/soulsync:latest";
          environment = {
            "PGID" = "1000";
            "PUID" = "1000";
            "PYTHONPATH" = "/app";
            "SOULSYNC_CONFIG_PATH" = "/app/config/config.json";
            "SOULSYNC_SPOTIFY_CALLBACK_PORT" = "8888";
            "SOULSYNC_TIDAL_CALLBACK_PORT" = "8889";
            "TZ" = "America/Chicago";
            "UMASK" = "022";
          };
          volumes = [
            "/shares/data/docker/soulsync/config:/app/config"
            "/shares/data/docker/soulsync/logs:/app/logs"
            "/shares/data/downloads:/app/downloads"
            "/shares/data/music:/app/Staging"
            "/shares/data/musicVideos:/app/MusicVideos"
            "/shares/data/docker/soulsync/scripts:/app/scripts"
            "/shares/data/movies:/media/movies"
            "/shares/data/tv:/media/tv"
            "/shares/data/youtube:/media/youtube"
            "/shares/data/docker/soulsync/database:/app/data"
          ];
          ports = [
            "8008:8008/tcp"
            "8888:8888/tcp"
            "8889:8889/tcp"
          ];
          log-driver = "journald";
          extraOptions = [
            "--add-host=host.docker.internal:host-gateway"
            "--cpus=2"
            "--health-cmd=[\"curl\", \"-f\", \"http://localhost:8008/\"]"
            "--health-interval=30s"
            "--health-retries=3"
            "--health-start-period=1m0s"
            "--health-timeout=10s"
            "--memory-reservation=536870912b"
            "--memory=2147483648b"
            "--network-alias=soulsync"
            "--network=soulsync-network"
          ];
        };
        systemd.services."docker-soulsync-webui" = {
          serviceConfig = {
            Restart = lib.mkOverride 90 "always";
            RestartMaxDelaySec = lib.mkOverride 90 "1m";
            RestartSec = lib.mkOverride 90 "100ms";
            RestartSteps = lib.mkOverride 90 9;
          };
          unitConfig.Description = "Container soulsync-webui generated by compose2nix.";
          after = [
            "docker-network-soulsync-network.service"
            "docker-volume-soulsync_soulsync_database.service"
          ];
          requires = [
            "docker-network-soulsync-network.service"
            "docker-volume-soulsync_soulsync_database.service"
          ];
          partOf = [
            "docker-compose-soulsync-root.target"
          ];
          wantedBy = [
            "docker-compose-soulsync-root.target"
          ];
        };

        # Networks
        systemd.services."docker-network-soulsync-network" = {
          unitConfig.Description = "Network soulsync-network generated by compose2nix.";
          path = [ pkgs.docker ];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            ExecStop = "docker network rm -f soulsync-network";
          };
          script = ''
            docker network inspect soulsync-network || docker network create soulsync-network
          '';
          partOf = [ "docker-compose-soulsync-root.target" ];
          wantedBy = [ "docker-compose-soulsync-root.target" ];
        };

        # Volumes
        systemd.services."docker-volume-soulsync_soulsync_database" = {
          unitConfig.Description = "Volume soulsync_soulsync_database generated by compose2nix.";
          path = [ pkgs.docker ];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
          };
          script = ''
            docker volume inspect soulsync_soulsync_database || docker volume create soulsync_soulsync_database --driver=local
          '';
          partOf = [ "docker-compose-soulsync-root.target" ];
          wantedBy = [ "docker-compose-soulsync-root.target" ];
        };

        # Root service
        # When started, this will automatically create all resources and start
        # the containers. When stopped, this will teardown all resources.
        systemd.targets."docker-compose-soulsync-root" = {
          unitConfig = {
            Description = "Root target generated by compose2nix.";
          };
          wantedBy = [ "multi-user.target" ];
        };
      }
    );
    homeModules.soulsync = moduleWithSystem (
      perSystem@{ ... }:
      _: {
      }
    );
  };
}
