royell_vpn: ENC[AES256_GCM,data:xMbYFwRlpi28I/gjXr29YPxV8SR17xHLSijqUetbDcuZkvmya9ajeN9WDXGHYwzTXAORoaxqXucL9O0xonPvzwkdQGWgK9pMxGRowCUFhVkgjav7qAwqpmlAreY1gR/Rt5gp76rNb0xSdh5wuc04Gy6Rc8bWiqJltYZlnwafIOJP3QhcsgO/ZnwmsJ7yVd7j+m8/FLyvNPZ30gtI/c4KyDKDsuP8YTs0EKX/lDXuw0Zv/QEZAUCe6vDQpIlX3/5vHZiArEBsReZMk/C1tFk40zo6eigzKX41KeLqKXUTaYNJaZZ765PIcGsxmMUtKYnFv7DVZoqEkZlNNDoHNwq508/U+xtB/tAzwHhnPfRG104uUe9hEY1bCM3J5BgH/8n1gXd3AR/3pCh2Rj3V5MT/rcLXpy0SyN0ijE+I1l63cZe0gxFrTBhtHi+uxqdZXoYEajzjwoGns/mM/qemBLzqn/Dr61sYAyMKYA36hgflhF80C6H51qFX15hRNgfFRll57inYnpuTs7RZYqCq8J0oKVqU82sR3+EBnhW22EKcaCR98OvR2gGVlNeL6KrKzSHWwoaSkgCRskgKY7L+9Y7bkmLRS/lKE7QuzIqwSHV3e7owcXAZX56sXg==,iv:bzAj+03I1NmJDM2ooazj2vKKnObi8h0pef8jWReUL5o=,tag:5Da9ORe3tnAr5dPi5KqDng==,type:str]
da_psk: ENC[AES256_GCM,data:1XS6VEa6wNHwVZVHTOVnlhI4yrlMUJlvFxDoEhRcTWqG/cXqHIob2xWx0zqwCvOXN5EIH4hiXw5DtPH9SLeD7snY51FsSzY8xi5M8jQuFaMHcfSxoNrJ5vwrLTxACtruaggwJZlyt2aQV4CMWShNcjzdHB93dhEmzU0UTuSoW0KhatIAJIbJMUl9T9zAdrIixYUSFO5uql2AVWLkJiiIWptrnpzg4rlRTtDshqgkIVQGIm4OfVOKBJtzkNpZf17aYnvkvMTX1A30FdUcg5ZARUBGAl0of6YweZNZHratu7C2gkRC2TdxKkDKvJwolim+A2X5IMAqCDsjuxWXg2t2E+39g5GRp9H73LwpcE2GB76ZmbijpMWF9yl72HrxwhZI7ZqzSatesYQhv7aOXLoTLXgPqwdW8TILZnmi7UMIVmAVkzNBlw==,iv:45Gg3zrF3iAUugJbAU+xfYCqSEplBEH/Kmb9O7oWDMU=,tag:F7eOsJAcjyPu6xVVlOKoxA==,type:str]
office_psk: ENC[AES256_GCM,data:m4QmEzgGxwSa6EYv+rlL8U9UTiiJFen48Smk1o7vSRuQTJy/anFGp/aG4zLOXBST/iWA3vT9gAhvsFKvYO1DEe9LZHD/i507+26pI2IAFZNS92rKTru3R06i1KW/ZwCtEYjKD+CA9VKaenMnz4Ob/CxJ533/WzFjV83SSyM69PHxlQL4KWLvkCHBT5lVznsGYLYZgCl+1hRrSzsQTGuXnobOksdVqUVQZUoWNKKzyFiOklu5sUzBoErsprN96hoYJ9DgX3o5v0JnZvYs/NSMltYHDyQUmDdYiXfZdua3rHIk8qK9WQP1f27ljoHui7lYTs/NqTT7qGihIlhyPFt1tTEhSJ5l3eeZzSI=,iv:Fr+aRBRxclXUvujw4vxM4zx0zzHFrgwG9JJh8+k7tVc=,tag:ssnaSvLkXeqckYLaz1JPog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nny857q3ujh77zved353ufzte5clv444783m6jc4xthmn43r75wqcputn0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNTNMVENvZGtTcGtGVmtH
            MkRnbkFkYm1LQ0NSNmMyUUtHWXFQU25oTWk0CitTbURBY0xzdUkxYkJIeS83MzQ3
            emNOb0s2dnJZK3RNM2k5dHhRS3ZXdkkKLS0tIEJtQUMrY1NvK3dTREptNm8xZXhN
            SXNmQmJGYk8vUHk1YUR5T0tCdUI5VlUKG7cWoy4cECSQPFsMIMTXdeOCWa+xN6cp
            gwJHMqCTMQY9BDlGpU8cLJRekFD6sAnCsngAHZIPv7gTv3ueT7JoaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1et3rsqjzt2z70vt0p8p4jcm47ms8e22um57vj5nvfpss58zwlcfsmcddrt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTjA1ZWtPSlNaU0VONkp4
            WkhDY1BWRTlZUTZKSTI4aDhmZkJZMmVEaUdvClovcnJvVlZ2OWdha293azNzUGRZ
            QUxIQzlOYjB3ZUd0WkRrV0RrMDFuWTAKLS0tIHBUYTVPN0lMMjdvZWc3dzY2K24x
            d0srQ01wN2cwS3pHSXRWMzJUdlRZMUUKit3YheyuLfJmRGCzQ6Ym74V4SM3XPxz9
            QRKYYpvsWrND7vhWiv58AWXJegndVM6ao4yXGY4yMpwz4KaxE77T3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-23T13:25:51Z"
    mac: ENC[AES256_GCM,data:xA3tJbopyVPfZcEOMz528292HVwjOVlOcUvqTxPTar0zYoFgI9pLUYN7G9E1WheNskBXNR7bVjxKMkXOSANXqmKVf445Q/T5Csvtzzo49xRUrxHU8vZxgE4UPjdfczpnaKDhtnx84aQUXeV2JxH+OuK8DW+MKWz/IItf4ls3X1o=,iv:XvuggtntnqtkK/Bj+eux9G080XdSebR9XuT+b9ateqw=,tag:5Yw9LCXF62hDiL4b0ewTuQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
