# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ channels, ... }:
self: super: let
  inherit (builtins) fetchurl;
  inherit (super.python310Packages) buildPythonPackage six;
in {
  python310Packages = super.python310Packages // {
    "tendo" = buildPythonPackage rec {
      pname = "tendo";
      version = "0.3.0";
      src = fetchurl {
        url = "https://files.pythonhosted.org/packages/ce/3f/761077d55732b0b1a673b15d4fdaa947a7c1eb5c9a23b7142df557019823/tendo-0.3.0-py3-none-any.whl";
        sha256 = "1rrvp5w2w3i697zjkqrl3cy9ij40qbas4gqjqakrsk7aanrp0sq2";
      };
      format = "wheel";
      doCheck = false;
      buildInputs = [];
      checkInputs = [];
      nativeBuildInputs = [];
      propagatedBuildInputs = [
        six
      ];
    };
  };
}
