traefik_env: ENC[AES256_GCM,data:istbrFsPk0TIcI2xLpJI+s0Dpj2RMFp2LfMdZkWaUIwteytzHzxp6rr2TyjzctrthCJGLZy2fDZfCP1KbBTyMBMLwP4t3SvkhFVXPrPIPXogcw//52ZIShJ3MQ==,iv:lbq7UBtDkI79gHDCsOAfodFH1BTSqd12xv0wnNp1iIw=,tag:t8leHoPM9wI1J1Ev01chyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBajVnYzdwOWtsZ1VHMlY5
            SDJPMmcvbXBMQ1gxY25FL2lta2VEUy96UGp3Ck9aM0N5TnVxWGV1eHZMUlQ1bi9L
            aU1JcUZxNm9EblhkVEZXMHU3SnBWaGsKLS0tIGJvWTBxR2F6S2Y0UzRoVGszWGY2
            Uy94U3h4VFhrZFZnaEZYVnM4d0VKamsKPZXvwG+LbLqEzwuxsxGxly5UMd1ALYk9
            CJO9oZDXAanfq6yEO3hXb0cnk4trDkdK+qtEKQyV5mk3pT6zDgNHgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nny857q3ujh77zved353ufzte5clv444783m6jc4xthmn43r75wqcputn0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBME1LcTZvSEpxb01NVmpa
            TjJHQnlLOE81NkJIWG1QSVp2UnhPZW1RWHpvCkdwaTJKSDkzRUFiY1JqR3ZzOTNk
            WjV2eVdRejhGRVdSaE9pNFh4TStydEkKLS0tIGFOM1ZadDVFU2U0NGlYRXJTTWhx
            NDFMdC81MUhTaEozVnpLV3pGcHQ1NUkKMPgF62c2e/IfXwMqYUALz/+VOSbFgVvN
            YiXiPp4DrkxI4U4dag+Wu57/AbJZC66soK05HMfnik+fRdoo0RvCXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1et3rsqjzt2z70vt0p8p4jcm47ms8e22um57vj5nvfpss58zwlcfsmcddrt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweFZVeEVkZEVPVVNzRVdL
            NjIrN3RmVDRJVjZuWWZ5dkZMeDIvZGl4bjIwCkpaRHZsSDFvbkF6c3VCcFhacDlO
            UDZNV3d1cEJ1eG95ZGxIb29oL2djZFUKLS0tIFEyUE13cE9hTFJQS01sZVhBazVo
            ZXM0THFFSk5uV3dYVUhZWC9vOUswaWMKpQOEfsCIPUi0t1fJHuXEqsNd4VC+cSxF
            43cfV7hTdOkMQELv+TWYnlWB6QxQcCSxeDXinJaZAbNGcy7Dqqz5qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tj460ln353gy48end4dl0efqf28z2ntwxu5we7qkauw472dax9xsvmwmhq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaDFzNTNtdVFRR2REUzJO
            eXpDWEpNQko5a1k2cHlZbWVpV3JqYmtTSEhrClJNTFg2MGdBZy9VSjJOdC9qdzJI
            UDZwMi8yTUFWQitQNzhaYjJrenpqWFkKLS0tIFJQaVFiNjF3UGhJKzR4cG9IamZL
            cjc4L1VDVnZSeWNqMGtCbmd5NFFSeUkKl/B7/nFp8TkXdN2yFve37QruZIxCKG9T
            oXQgb/A+Lu1aZ8y3SBebBLZNToeo/5k5KIu/yytFE/cLTbIKzW9OIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14lru46n84vakjj2mjah3ewftjt33fwr2km9g75a3lcpw8af4yawq6n6uag
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZEtobzdCMTE4OXlLTXd1
            TU5yUXE5MzVJWTV3bnljWVplZnNLd3NqSlJnCldNSVJWek4xUXNSRTExazFvcmE2
            dFdvY05KQzdVeXVaMDYwbkFZU0svazgKLS0tIFBlVGZPWVo2MkVTQ3h3WXNVN1No
            NkROMnc0c2U5aDExbW1UK2RveXpQcUEKyp7OZpjT7H3v7JLCA3y2Al/cZOTOIYXP
            QQIhImYQ6zRXW99NsL+XdgQ61ItMARDHXpsRpjfbjR8izd//F+mbCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17ygl4us55m6nu4vrqd8s28snaqnkrcp6unyenlmj3wc4r0nms3es4vd39g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR0czZzV6Qm5Id1NYYW9B
            NHdTTSswdXpJSFZ1bnRXVXROblBnRlJkUXdVCmQ5TFBnallTWnhrTmx0YnNSWVhW
            Vk84YTJIeU9vbUkwUlRHZVhqRXBzMHMKLS0tIHQySWdlZC9pREN3L2NLZWJUNWwr
            cjhoY3VPai91NXJ4Nk1qZEFQeGI0ZG8Kx3mIL6/7semkpVMf9BFwPk4K3kTLknTc
            UoHhZI9YsZCFSmlnvcYmcMfIjmCiiN1h3CeVS3KbsRsp9X7sFKIwDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13exnaeq7ftcskap67kml5jgv7vxxdgjjf22f9ugypxh3jesm9ars0l9jeh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdTZXcG9paHZjNTJBYkxH
            R0pzY3hrcjNCVmVCT1hpU1BleXNGejRLdEdJCmxMclg4OWdYb2ZLdTlIb1JhWThP
            SmJBL1FSczVqRXZXaHh5REx0MHFBcUkKLS0tIHdhZ0l4SXUxL2t4a1JkRDBqUUJV
            Y3JNR3hRUWU5M1hLK0RUZ3FvOUlQSjgKHBw1owT3DcmR1mUx2gUB5S0q6NoiwaKD
            sHnU/9h8RQRQXSBABp3ckmLDb5gixUO1CcoYoy06hLXGB5nqvGFsxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13xc4axyyg8wdwvtvx54cxdcfnlcwxrjcns4dfsrpe0vs0dcn8enqv8fuhz
    lastmodified: "2026-08-24T16:23:04Z"
    mac: ENC[AES256_GCM,data:TchNa5KKmpMJXf6547z78zyDE4t65iTmD7/063/GmQVxLCaou8TSIanQMsN6c+W79zWp17oIeGF0pD0pxYpc5rs0KUqGztblBXFz1Ol+ghaKpNRTbum/f6UR0D//wJH3rm/MBP6zifo7U0QMEyADhWkAPC9wSeFKckPnu3q7O68=,iv:X37e4wtWMo7Fihe8rMxtm0jYfUmLwPXEJjF4T9JAe4g=,tag:pv4icay+xQQlxWtoVKje0g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
