require("plugins.ui.bufferline")
require("plugins.ui.dressing")
require("plugins.ui.ibl")
-- require("plugins.ui.indentscope")
-- require("plugins.ui.lazygit")
require("plugins.ui.lualine")
-- require("plugins.ui.neogit")
-- require("plugins.ui.noice")
require("plugins.ui.notify")
require("plugins.ui.transparent")
